# Generated by Django 3.0.3 on 2020-03-24 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pfapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='acctype',
            name='User_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pfapp.Person'),
            preserve_default=False,
        ),
    ]
