# Generated by Django 3.0.3 on 2020-04-25 07:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pfapp', '0005_user_details_u_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_details',
            name='u_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pfapp.Person'),
        ),
    ]
