# Generated by Django 3.0.3 on 2020-04-25 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pfapp', '0006_auto_20200425_1246'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_details',
            name='dob',
        ),
        migrations.RemoveField(
            model_name='user_locations',
            name='location',
        ),
        migrations.AddField(
            model_name='user_details',
            name='phoneno',
            field=models.CharField(default='xxxxxxxxxx', max_length=13),
        ),
        migrations.AddField(
            model_name='user_locations',
            name='country',
            field=models.CharField(default='xxxxxxxxxx', max_length=30),
        ),
        migrations.AddField(
            model_name='user_locations',
            name='district',
            field=models.CharField(default='xxxxxxxxxx', max_length=30),
        ),
        migrations.AddField(
            model_name='user_locations',
            name='locality',
            field=models.CharField(default='xxxxxxxxxx', max_length=30),
        ),
        migrations.AddField(
            model_name='user_locations',
            name='state',
            field=models.CharField(default='xxxxxxxxxx', max_length=30),
        ),
    ]
