# Generated by Django 3.0.3 on 2020-05-09 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pfapp', '0008_auto_20200506_1357'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_details',
            old_name='u_id',
            new_name='person',
        ),
        migrations.RenameField(
            model_name='user_locations',
            old_name='u_id',
            new_name='person',
        ),
    ]
